name: nopCommerce automation
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Build and start Selenium Docker container
        run: |
          docker run -d \
            --add-host host.docker.internal:host-gateway \
            -p 4444:4444 \
            -p 5900:5900 \
            --shm-size="2g" \
            selenium/standalone-chrome:4.2.1-20220531        

      - name: Start nopCommerce application
        run: python nop_commerce/nop_commerce.py

      - name: Run the tests
        run:
          python -m pytest --junit-xml=report.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/*.xml'


     

  
